name = "app-blackroad"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

[vars]
AUTH_URL = "https://auth-blackroad.amundsonalexa.workers.dev"
PAY_URL = "https://roadpay.amundsonalexa.workers.dev"
CHAT_URL = "https://chat-blackroad.amundsonalexa.workers.dev"
