name = "os-blackroad"
main = "src/worker.js"
compatibility_date = "2026-03-31"

[[routes]]
pattern = "os.blackroad.io/*"
zone_name = "blackroad.io"

[[d1_databases]]
binding = "DB"
database_name = "blackroad-os-analytics"
database_id = "a244526c-d9b4-48aa-854e-c7132080dd8a"
